---
- name: Install and configure nginx for static website hosting
  hosts: gcp
  become: yes

  tasks:
    - name: Debug file location
      debug:
        msg: "{{ playbook_dir }}/files/static-site-config"
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Add user to group root
      user:
        name: "{{ user }}"
        groups: root
        state: present

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Check host
      action: command /usr/bin/whoami        

    - name: Add nginx configuration
      copy:
        src: static-site-config
        dest: /etc/nginx/sites-available/
        owner: "{{ user }}"
        group: root
        mode: '0644'

    - name: Enable website configuration
      file:
        src: /etc/nginx/sites-available/static-site-config
        dest: /etc/nginx/sites-enabled/static-site-config
        state: link

    - name: Ensure nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes
  vars:
    user: "nginx"